apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cms_test
  annotations:
    github.com/project-slug: YashrajPawar/cms_test
spec:
  type: other
  lifecycle: unknown
  owner: YashrajPawar
