apiVersion: backstage.io/v1beta2
kind: Template
# some metadata about the template itself
metadata:
  name: yashraj
  title: Test Action template
  description: scaffolder v1beta2 template demo
  annotations:
    backstage.io/time-saved: PT4H
spec:
  owner: backstage/techdocs-core
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Creating S3 Bucket
      required:
        - name
      properties:
        name:
          title: Yashraj
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5

  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: createBucket
      name: Create Bucket
      action: AWS::S3::Bucket
      Properties:
        BucketName: DOC-EXAMPLE-BUCKET
