AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: Examplemvinrini-swkno

Outputs:
  BucketName:
    Description: Name of the created S3 Bucket
    Value: !Ref MyS3Bucket

