apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: s3-bucket
  title: Create S3 Bucket
  description: This template creates an S3 bucket in AWS using CloudFormation.
  tags:
    - aws
    - s3
spec:
  owner: excelfore
  type: service
  parameters:
    - title: Bucket Configuration
      required:
        - bucketName
        - region
      properties:
        bucketName:
          type: string
          title: Bucket Name
          description: The name of the S3 bucket to create.
        region:
          type: string
          title: AWS Region
          description: The AWS region where the bucket will be created.
  steps:
    - id: create-s3-bucket
      name: Create S3 Bucket
      action: scaffolder:execute
      input:
        script: |
          #!/bin/bash
          set -e
          BUCKET_NAME=${{ parameters.bucketName }}
          REGION=${{ parameters.region }}
          aws s3api create-bucket --bucket $BUCKET_NAME --region $REGION --create-bucket-configuration LocationConstraint=$REGION
