apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-s3-bucket
  title: Create S3 Bucket
  description: This template creates an S3 bucket in AWS using CloudFormation.
  tags:
    - aws
    - s3
spec:
  owner: your-team@example.com
  type: service
  parameters:
    - title: Bucket Configuration
      required:
        - bucketName
        - region
      properties:
        bucketName:
          type: string
          title: Bucket Name
          description: The name of the S3 bucket to create.
        region:
          type: string
          title: AWS Region
          description: The AWS region where the bucket will be created.
  steps:     
    - id: create-bucket
      title: Create S3 Bucket
      script: |
        aws s3 mb s3://${parameters.bucketName} --region ${parameters.region}
        echo "S3 bucket '${parameters.bucketName}' created in region '${parameters.region}'"





