apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: s3-bucket
  title: Create S3 Bucket
  description: This template creates an S3 bucket in AWS using CloudFormation.
  tags:
    - aws
    - s3
spec:
  owner: excelfore
  type: service
  parameters:
    - title: Bucket Configuration
      required:
        - region
      properties:
        bucketName:
          type: string
          title: Bucket Name
          description: The name of the S3 bucket to create.
        region:
          type: string
          title: AWS Region
          description: The AWS region where the bucket will be created.
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./s3bucket.yaml


    - id: fetch-docs
      name: Fetch Docs
      action: fetch:plain
      input:
        targetPath: ./community
        url: https://github.com/YashrajPawar/cms_test/blob/master/cms_sample/.acdp/s3bucket.yaml
