apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-s3-bucket
  title: Create S3 Bucket
  description: Create a new S3 bucket in AWS
  tags:
    - aws
    - s3
spec:
  owner: your-username # Replace with your Backstage username
  type: service
  parameters:
    - title: Bucket Details
      required:
        - BucketName
        - Region
      properties:
        BucketName:
          title: Bucket Name
          type: string
          description: Name of the S3 bucket (must be unique globally)
          ui:autofocus: true
          ui:options:
            pattern: ^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$  # Valid bucket name regex
        Region:
          title: AWS Region
          type: string
          description: Region where the bucket will be created (e.g., us-east-1)
  action:
    title: Action
    type: string
    description: What action do you want to perform?
    enum:
      - create
      - destroy  # Optional, for future destroy functionality
  steps:
    - id: create-bucket
      title: Create S3 Bucket
      script: |  # Shell script using AWS CLI (replace with your chosen tool)
        aws s3 mb s3://${parameters.BucketName} --region ${parameters.Region}
        echo "S3 bucket '${parameters.BucketName}' created in region '${parameters.Region}'"

